### PR TITLE
Adding nuclei scanner

### PR DESCRIPTION
**Pull request by bauthard**

### CODE REVIEW

**Comment by qazbnm456** [comment]
It's a good project indeed, @bauthard. Would you mind updating other README files together? Thanks!

**Comment by bauthard** [comment]
@qazbnm456 I've updated other readme files as well, thank you.

**Comment by qazbnm456** [comment]
Neat! Could also modify a little bit of the rear part of the desc to "ease of use by [@projectdiscovery](https://github.com/projectdiscovery)." Thanks!

**Comment by bauthard** [comment]
done @qazbnm456

**Comment by qazbnm456** [comment]
Merged, thanks!

**Pull request merged**
