### PR TITLE
Added Security Cheatsheet.

### PR DESCRIPTION
**Pull request by uppusaikiran**
- This cheatsheet is updated on a daily basis.

### CODE REVIEW

**Comment by qazbnm456** [comment]
Sorry for the late reply. Could you move your item under section #Cheetsheets? Besides, don't forget to update the other two readme files at the same time. Thanks for your contribution. 😄

**Comment by uppusaikiran** [comment]
@qazbnm456 Updated in all 3 files.

**Comment by qazbnm456** [comment]
Sorry for bothering, @uppusaikiran, but I've just created that [section](https://github.com/qazbnm456/awesome-web-security#cheetsheets). Could you move your item beneath it? Thanks!

**Comment by uppusaikiran** [comment]
I am creating a new PR. Closing this.

**Pull request closed without merging**
