### PR TITLE
Added SSL/TLS practical tutorial 

### PR DESCRIPTION
**Pull request by Hakky54**
Added an example project which has no security.
It provides how-to steps to enable encryption with SSL/TLS for three scenarios:
- one way authentication - server communicates over https and identifies itself with a certificate
- two way authentication - both server and client needs to identify itself and trust each other
- two way authentication based on trusting the certificate authority - same as above one but trusting the root-ca is enough to get the same result

Java spring based web server
A variation of http clients which are supported

Helps the person to learn about certificates, keystores, ssl commands and basic web security based on certificates.

### CODE REVIEW

**Comment by Hakky54** [comment]
@qazbnm45 have you had a chance to look at this, anything you want done differently?

**Comment by Hakky54** [comment]
@qazbnm456 have you had a chance to look at this, anything you want done differently?

**Comment by qazbnm456** [comment]
Sorry for the late reply, @Hakky54! I'll give it a quick review asap. Thanks for your contribution. :smile:

**Comment by Hakky54** [comment]
Thank you!

I just pulled the latest changes from your master and pushed it back here. I noticed that there is a separate section for SSL/TLS within the Introduction section. I placed my changes under the following section:
- Practices -> Application -> Encrypting with SSL/TLS

But you you think it should be under Introduction?
- Introduction -> SSL/TLS  -> Encrypting with SSL/TLS

And what do you think about the title, do you think it is describing enough or would you have it differently?

**Comment by qazbnm456** [comment]
I think it should be placed under the introduction section, @Hakky54. In addition to that, could you change the title to "Practical introduction to SSL/TLS"? It would be more suitable to describe your project I considered.
And, add an "@" before your id to indicate the author's homepage is from either GitHub or Twitter.

On top of all that, you've really provided good material to comprehensively introduce SSL/TLS. Thanks for the contrib, @Hakky54!

Once you make the changes, I'll merge it into the list. 😃

**Comment by Hakky54** [comment]
Thank you @qazbnm456 for the compliments 😃, I actually need to thank you for providing this kind of project as a starting point for all of us who are in the need for more knowledge!

I applied your feedback, thank you. The titel makes more sense now

**Comment by qazbnm456** [comment]
Oops, you don't need to commit the `.gitignore` file, @Hakky54. 😄

**Comment by Hakky54** [comment]
Ah I didn't know it was not ok to adjust the gitignore. I reverted it now, so hopefully everything else is still ok.

**Comment by qazbnm456** [comment]
Merged! 🥳

**Comment by Hakky54** [comment]
Thank you very much!

**Pull request merged**
