### PR TITLE
Addition of some more awesome stuffs + Changes to Non-Existent Ones

### PR DESCRIPTION
**Pull request by 0xInfection**
Addition of some new tools and writeups, and change to non-existent tools and stuff.

### CODE REVIEW

**Comment by qazbnm456** [comment]
Thank you for your comments! btw, would you mind updating other README files and changing the title 'Penetrating' to 'Penetration Testing' as well?

**Comment by theInfectedDrake** [comment]
I really extend my thankfulness for featuring my [TIDoS-Framework](https://github.com/theInfectedDrake/TIDoS-Framework) in your list. I forgot the courtesies, sorry for that.

Well I had decided to change my username to [theInfectedDrake](https://github.com/theInfectedDrake) from the-Infected-Drake. So the location of the toolkit too changed. 🙂.

And speaking of other README files, I assure to do them by tomorrow. In the meantime, mind taking a look at the proposed changes in the pull request and merging them?

**Comment by qazbnm456** [comment]
Then, would you mind making this PR clean to just cover the problem you mentioned, which is your handle and the link to your project? And opening another PR to fix up other things if you'd like to. @theInfectedDrake 😄

**Comment by theInfectedDrake** [comment]
Okay so lets close this PR and let me open up other two. I assure I will do the other README files at once.

**Pull request closed without merging**
