### PR TITLE
Added Raccoon - a new tool for OSINT

### PR DESCRIPTION
**Pull request by evyatarmeged**
https://github.com/evyatarmeged/Raccoon

### CODE REVIEW

**Comment by theInfectedDrake** [comment]
Well there are hundreds of tools out there and yours is no different. Consider upgrading your tool before making a contribution. 

Lets see what @qazbnm456 has to say.

**Comment by theInfectedDrake** [comment]
Well there are hundreds of tools out there and yours is no different. Consider upgrading your tool before making a contribution. 

Lets see what @qazbnm456 has to say.

**Comment by evyatarmeged** [comment]
Hey @theInfectedDrake, thanks for the feedback. I'll keep this open until @qazbnm456 responds then.

**Comment by qazbnm456** [comment]
@evyatarmeged @theInfectedDrake Hi, thanks for your opinions and contributions. I'd like to encourage all tools made by their authors' own hands and will add them into this curated list for now if they're not that bad.

However, I do plan to clean up this curated list and remove some duplicate or redundant entries in the near future to make sure all the things listed here are still awesome. That's quite a huge work definitely.

**Pull request merged**
