### PR TITLE
Added WAScan. Fixed punctuation.

### PR DESCRIPTION
**Pull request by okiwan**
WAScan is simple to use yet interesting, at least for small projects.

### CODE REVIEW

**Comment by qazbnm456** [comment]
Hi @okiwan, thanks for your contribution!

Would you mind moving the entry to the new section "Scanning"? I've added this new section and think it might be more suitable to have your suggested tool listed there.

**Comment by okiwan** [comment]
Done. I hope this will be OK.

**Comment by qazbnm456** [comment]
Almost! You have to modify this (`@m4ll0k`) to this (`[@m4ll0k](https://github.com/m4ll0k)`] as well. Thanks.

**Comment by okiwan** [comment]
All right, that should do it. Sorry for the inconvenience.

**Comment by qazbnm456** [comment]
@okiwan, thanks for your swift revises! Have a great day.

**Pull request merged**
