### PR TITLE
Add tl;dr sec to list of blogs

### PR DESCRIPTION
**Pull request by clintgibler**
Hey! 👋 Thanks so much for putting together this repo, tons of awesome resources here 🙏 

This PR adds a link to a newsletter/blog I write that aims to collect useful security tools, blog posts, and current research to help people keep up with the massive amount of content out there. 

It covers a number of security areas, not just web security, so let me know if it isn't a good fit for this list. No problem if not :) 

Here's an example of some previous web security content: 
  https://tldrsec.com/blog/tldr-sec-044/#towards-native-security-defenses-for-the-web-ecosystem.

### CODE REVIEW

**Comment by qazbnm456** [comment]
Thanks for you contrib, @clintgibler. To me, it seems that it's more suitable to be placed under the **Digests** section. What do you think?

**Comment by clintgibler** [comment]
Thanks for your quick response @qazbnm456! I was debating about putting it under Blogs vs Digests, and I think you're right, Digests makes more sense. I pushed an update :)

**Comment by qazbnm456** [comment]
Merged! 🎉 Thank you.

**Comment by clintgibler** [comment]
Thank you! 🙏

**Pull request merged**
